import assert from 'node:assert/strict';
import {createCameraSession, captureCameraPhoto, cameraErrorMessage} from './cameraCapture.js';
let stopped = 0;
const stream = {getTracks: () => [{stop: () => stopped++}]};
let constraints;
const session = createCameraSession({getUserMedia: async value => {constraints = value; return stream;}});
assert.equal(await session.start(), stream);
assert.deepEqual(constraints, {video: {facingMode: 'user'}, audio: false});
session.stop(); session.stop(); assert.equal(stopped, 1);
let resolve;
const pending = createCameraSession({getUserMedia: () => new Promise(done => {resolve = done;})});
const result = pending.start(); pending.stop(); resolve(stream);
assert.equal(await result, null); assert.equal(stopped, 2);
await assert.rejects(createCameraSession({}).start(), /unavailable/);
await assert.rejects(createCameraSession({getUserMedia: async () => {throw Object.assign(new Error(), {name: 'NotAllowedError'});}}).start());
assert.match(cameraErrorMessage({name: 'NotAllowedError'}), /denied/);
let drawing;
const canvas = {getContext: () => ({drawImage: (...args) => {drawing = args;}}), toBlob: done => done(new Blob(['photo'], {type: 'image/jpeg'}))};
const video = {videoWidth: 640, videoHeight: 480};
const photo = await captureCameraPhoto(video, canvas);
assert.equal(photo.type, 'image/jpeg'); assert.equal(photo.size, 5);
assert.equal(canvas.width, 640); assert.equal(canvas.height, 480);
assert.equal(drawing[0], video);
await assert.rejects(captureCameraPhoto({videoWidth: 0}, canvas), /starting/);
await assert.rejects(captureCameraPhoto(video, {...canvas, toBlob: done => done(null)}), /Could not capture/);
console.log('PASS camera session permissions, late cleanup, capture File, and error paths');
const {createPhotoCaptureAttempt} = await import('./cameraCapture.js');
let finishPhoto;
let attachedCount = 0;
const captureAttempt = createPhotoCaptureAttempt();
const pendingPhoto = captureAttempt.run(() => new Promise(resolve => {finishPhoto = resolve;}), () => {attachedCount++;});
captureAttempt.cancel();
finishPhoto(photo);
assert.equal(await pendingPhoto, false);
assert.equal(attachedCount, 0, 'Cancel during canvas capture must not attach the photo');
const liveAttempt = createPhotoCaptureAttempt();
assert.equal(await liveAttempt.run(async () => photo, () => {attachedCount++;}), true);
assert.equal(attachedCount, 1);
console.log('PASS cancelled pending photo does not attach');
