import assert from 'node:assert/strict';
import {registerNavigationGroup,listNavigationTabs,selectRegisteredTab} from './navigationRegistry.js';
let selected='';
const remove=registerNavigationGroup({windowId:'w',containerId:'report',tabs:[{id:'market',label:'Open Market'}],select:id=>{selected=id;}});
assert.deepEqual(listNavigationTabs('w'),[{containerId:'report',tabId:'market',title:'Open Market'}]);
assert.equal(selectRegisteredTab({windowId:'w',containerId:'report',tabId:'market'}),true);
assert.equal(selected,'market');
assert.throws(()=>selectRegisteredTab({windowId:'w',containerId:'report',tabId:'invented'}),/not available/);
assert.equal(selectRegisteredTab({windowId:'other',tabId:'market'}),false);
const removeOther=registerNavigationGroup({windowId:'w',containerId:'other',tabs:[{id:'market',label:'Other'}],select:()=>{}});
assert.throws(()=>selectRegisteredTab({windowId:'w',tabId:'market'}),/ambiguous/);
removeOther();remove();assert.deepEqual(listNavigationTabs('w'),[]);
