export const reportPrintSchema = {
  $id: "report://schema/report-print/v1",
  $schema: "https://json-schema.org/draft/2020-12/schema",
  type: "object",
  additionalProperties: false,
  required: [
    "version",
    "kind",
    "specVersion",
    "specHash",
    "fillVersion",
    "fillHash",
    "source",
    "title",
    "pageGeometry",
    "pages",
    "bookmarks",
    "diagnostics",
  ],
  properties: {
    version: { type: "integer", minimum: 1 },
    kind: { const: "reportPrint" },
    specVersion: { type: "integer", minimum: 1 },
    specHash: { type: "string" },
    fillVersion: { type: "integer", minimum: 1 },
    fillHash: { type: "string" },
    source: { $ref: "#/$defs/source" },
    title: { type: "string" },
    pageGeometry: { $ref: "#/$defs/pageGeometry" },
    pages: {
      type: "array",
      minItems: 1,
      items: { $ref: "#/$defs/page" },
    },
    bookmarks: {
      type: "array",
      items: { $ref: "#/$defs/bookmark" },
    },
    diagnostics: {
      type: "array",
      items: { $ref: "#/$defs/diagnostic" },
    },
  },
  $defs: {
    source: {
      type: "object",
      additionalProperties: false,
      required: ["kind", "containerId", "stateKey", "dataSourceRef"],
      properties: {
        kind: { type: "string" },
        containerId: { type: "string" },
        stateKey: { type: "string" },
        dataSourceRef: { type: "string" },
      },
    },
    pageGeometry: {
      type: "object",
      additionalProperties: false,
      required: [
        "width",
        "height",
        "marginTop",
        "marginRight",
        "marginBottom",
        "marginLeft",
        "headerHeight",
        "footerHeight",
      ],
      properties: {
        width: { type: "number", minimum: 1 },
        height: { type: "number", minimum: 1 },
        marginTop: { type: "number", minimum: 0 },
        marginRight: { type: "number", minimum: 0 },
        marginBottom: { type: "number", minimum: 0 },
        marginLeft: { type: "number", minimum: 0 },
        headerHeight: { type: "number", minimum: 0 },
        footerHeight: { type: "number", minimum: 0 },
      },
    },
    box: {
      type: "object",
      additionalProperties: false,
      required: ["x", "y", "width", "height"],
      properties: {
        x: { type: "number", minimum: 0 },
        y: { type: "number", minimum: 0 },
        width: { type: "number", minimum: 0 },
        height: { type: "number", minimum: 0 },
      },
    },
    page: {
      type: "object",
      additionalProperties: false,
      required: ["number", "elements", "headerElements", "footerElements"],
      properties: {
        number: { type: "integer", minimum: 1 },
        elements: {
          type: "array",
          items: { $ref: "#/$defs/printElement" },
        },
        headerElements: {
          type: "array",
          items: { $ref: "#/$defs/printElement" },
        },
        footerElements: {
          type: "array",
          items: { $ref: "#/$defs/printElement" },
        },
      },
    },
    printElementBase: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box"],
      properties: {
        id: { type: "string" },
        kind: { type: "string" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
      },
    },
    textElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "text"],
      properties: {
        id: { type: "string" },
        kind: { const: "text" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        text: { type: "string" },
        fontFamily: { type: "string" },
        fontSize: { type: "number", minimum: 1 },
        fontWeight: { type: "string" },
        color: { type: "string" },
        align: { enum: ["left", "center", "right"] },
        verticalAlign: { enum: ["top", "middle", "bottom"] },
        wrap: { type: "boolean" },
      },
    },
    lineElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "strokeColor", "strokeWidth"],
      properties: {
        id: { type: "string" },
        kind: { const: "line" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        strokeColor: { type: "string" },
        strokeWidth: { type: "number", minimum: 0 },
        strokeStyle: { enum: ["solid", "dashed", "dotted"] },
      },
    },
    rectElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box"],
      properties: {
        id: { type: "string" },
        kind: { const: "rect" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        fillColor: { type: "string" },
        strokeColor: { type: "string" },
        strokeWidth: { type: "number", minimum: 0 },
        radius: { type: "number", minimum: 0 },
      },
    },
    imagePayload: {
      type: "object",
      additionalProperties: false,
      required: ["mimeType", "payload"],
      properties: {
        mimeType: { type: "string" },
        payload: { type: "string" },
      },
    },
    imageElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "image"],
      properties: {
        id: { type: "string" },
        kind: { const: "image" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        image: { $ref: "#/$defs/imagePayload" },
      },
    },
    svgElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "svg"],
      properties: {
        id: { type: "string" },
        kind: { const: "svg" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        svg: { type: "string" },
      },
    },
    tableCellTextElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "rowKey", "columnKey", "text"],
      properties: {
        id: { type: "string" },
        kind: { const: "tableCellText" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        rowKey: { type: "string" },
        columnKey: { type: "string" },
        text: { type: "string" },
        format: { type: "string" },
        align: { enum: ["left", "center", "right"] },
      },
    },
    tableCellDataBarElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "rowKey", "columnKey", "value", "min", "max", "fillColor"],
      properties: {
        id: { type: "string" },
        kind: { const: "tableCellDataBar" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        rowKey: { type: "string" },
        columnKey: { type: "string" },
        value: { type: "number" },
        min: { type: "number" },
        max: { type: "number" },
        fillColor: { type: "string" },
        backgroundColor: { type: "string" },
      },
    },
    tableCellToneElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "rowKey", "columnKey", "tone", "label", "backgroundColor"],
      properties: {
        id: { type: "string" },
        kind: { const: "tableCellTone" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        rowKey: { type: "string" },
        columnKey: { type: "string" },
        tone: { type: "string" },
        label: { type: "string" },
        backgroundColor: { type: "string" },
        borderColor: { type: "string" },
        textColor: { type: "string" },
      },
    },
    tableCellBadgeElement: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind", "box", "rowKey", "columnKey", "label"],
      properties: {
        id: { type: "string" },
        kind: { const: "tableCellBadge" },
        box: { $ref: "#/$defs/box" },
        zIndex: { type: "integer", minimum: 0 },
        rowKey: { type: "string" },
        columnKey: { type: "string" },
        label: { type: "string" },
        tone: { type: "string" },
        backgroundColor: { type: "string" },
        borderColor: { type: "string" },
        textColor: { type: "string" },
      },
    },
    printElement: {
      anyOf: [
        { $ref: "#/$defs/textElement" },
        { $ref: "#/$defs/lineElement" },
        { $ref: "#/$defs/rectElement" },
        { $ref: "#/$defs/imageElement" },
        { $ref: "#/$defs/svgElement" },
        { $ref: "#/$defs/tableCellTextElement" },
        { $ref: "#/$defs/tableCellDataBarElement" },
        { $ref: "#/$defs/tableCellToneElement" },
        { $ref: "#/$defs/tableCellBadgeElement" },
      ],
    },
    bookmark: {
      type: "object",
      additionalProperties: false,
      required: ["id", "title", "pageNumber"],
      properties: {
        id: { type: "string" },
        title: { type: "string" },
        pageNumber: { type: "integer", minimum: 1 },
        level: { type: "integer", minimum: 1 },
        elementId: { type: "string" },
        y: { type: "number", minimum: 0 },
      },
    },
    diagnostic: {
      type: "object",
      additionalProperties: false,
      required: ["code", "severity", "message"],
      properties: {
        code: { type: "string" },
        severity: { type: "string" },
        message: { type: "string" },
        pageNumber: { type: "integer", minimum: 1 },
        elementId: { type: "string" },
      },
    },
  },
};
