import assert from 'node:assert/strict';
import {resolveReportDateRangeValue, updateReportDateRangeValue} from './reportDateRangeValue.js';
import {getScopeParamValue, setScopeParamValue} from './scopeStateModel.js';
const now = new Date(2026, 8, 28, 12);
const preset = updateReportDateRangeValue({}, 'preset', 'last7Days', now);
assert.deepEqual(preset, {preset:'last7Days'});
assert.equal(resolveReportDateRangeValue(preset, now).start, '2026-09-22');
assert.equal(resolveReportDateRangeValue(preset, new Date(2026,8,29,12)).start, '2026-09-23');
let range = updateReportDateRangeValue({start:'2026-09-01',end:'2026-09-28'}, 'start', '7 days ago', now);
range = updateReportDateRangeValue(range, 'end', 'today', now);
assert.equal(range.startExpression, '7 days ago');
assert.equal(resolveReportDateRangeValue(range, now).start, '2026-09-21');
assert.equal(resolveReportDateRangeValue(range, new Date(2026,8,29,12)).start, '2026-09-22');
const explicit = updateReportDateRangeValue(range, 'start', '2026-09-01', now);
assert.equal(explicit.startExpression, undefined);
assert.equal(explicit.start, '2026-09-01');
assert.equal(updateReportDateRangeValue(preset, 'end', '2026-09-28', now).preset, undefined);
assert.equal(resolveReportDateRangeValue({startExpression:'invalid',end:'2026-09-28'}, now).start, '');
const stored = setScopeParamValue({}, 'dateRange', preset);
assert.equal(getScopeParamValue(stored, 'dateRange').preset, 'last7Days');
console.log('PASS: rolling date presets, persistent relative expressions, explicit date overrides, and invalid expression handling');
